# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(697, 496)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(697, 455))
        self.centralwidget.setMaximumSize(QtCore.QSize(697, 455))
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setContentsMargins(2, 2, 2, 2)
        self.formLayout.setSpacing(2)
        self.formLayout.setObjectName("formLayout")
        self.backgroundBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.backgroundBox.setMinimumSize(QtCore.QSize(691, 451))
        self.backgroundBox.setMaximumSize(QtCore.QSize(691, 451))
        self.backgroundBox.setStyleSheet("QGroupBox {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(226, 226, 226, 0.8), stop:1 rgba(201, 238, 255, 0.8));\n"
"}")
        self.backgroundBox.setTitle("")
        self.backgroundBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.backgroundBox.setObjectName("backgroundBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.backgroundBox)
        self.verticalLayout_2.setContentsMargins(140, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.loginBox = QtWidgets.QGroupBox(parent=self.backgroundBox)
        self.loginBox.setMinimumSize(QtCore.QSize(421, 351))
        self.loginBox.setMaximumSize(QtCore.QSize(421, 351))
        self.loginBox.setAutoFillBackground(False)
        self.loginBox.setStyleSheet("QGroupBox {\n"
"    padding: 30px;\n"
"    background: #fff;\n"
"    border-radius: 10px;\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n"
"    display: none;\n"
"}")
        self.loginBox.setTitle("")
        self.loginBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loginBox.setObjectName("loginBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.loginBox)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.loginBox)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.titleLabel.setAutoFillBackground(False)
        self.titleLabel.setStyleSheet("QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: #333;\n"
"    margin-bottom: 10px;\n"
"}")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.username_input = QtWidgets.QLineEdit(parent=self.loginBox)
        self.username_input.setStyleSheet("QLineEdit {\n"
"    width: 100%;\n"
"    padding: 12px;\n"
"    background: #eee;\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    outline: none;\n"
"    font-size: 16px;\n"
"    color: #333;\n"
"    margin-bottom: 20px;\n"
"}")
        self.username_input.setText("")
        self.username_input.setClearButtonEnabled(False)
        self.username_input.setObjectName("username_input")
        self.verticalLayout.addWidget(self.username_input)
        self.password_input = QtWidgets.QLineEdit(parent=self.loginBox)
        self.password_input.setStyleSheet("QLineEdit {\n"
"    width: 100%;\n"
"    padding: 12px;\n"
"    background: #eee;\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    outline: none;\n"
"    font-size: 16px;\n"
"    color: #333;\n"
"    margin-bottom: 20px;\n"
"}")
        self.password_input.setText("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_input.setObjectName("password_input")
        self.verticalLayout.addWidget(self.password_input)
        self.loginButton = QtWidgets.QPushButton(parent=self.loginBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(62)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton {\n"
"    padding: 12px;\n"
"    background: #74bcec;\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    cursor: pointer;\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout.addWidget(self.loginButton)
        self.verticalLayout_2.addWidget(self.loginBox)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.backgroundBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 697, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "Login"))
        self.username_input.setPlaceholderText(_translate("MainWindow", "Username"))
        self.password_input.setPlaceholderText(_translate("MainWindow", "Password"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
