from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(483, 285)
        MainWindow.setMinimumSize(QtCore.QSize(483, 285))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(483, 244))
        self.centralwidget.setMaximumSize(QtCore.QSize(483, 244))
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setContentsMargins(1, 1, 1, 1)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel.setMinimumSize(QtCore.QSize(481, 61))
        self.titleLabel.setMaximumSize(QtCore.QSize(481, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.titleLabel.setAutoFillBackground(False)
        self.titleLabel.setStyleSheet("QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 145, 217);\n"
"}")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.titleLabel)
        self.mainBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.mainBox.setMinimumSize(QtCore.QSize(481, 181))
        self.mainBox.setMaximumSize(QtCore.QSize(481, 181))
        self.mainBox.setAutoFillBackground(False)
        self.mainBox.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 145, 217);\n"
"    border: none;\n"
"}")
        self.mainBox.setTitle("")
        self.mainBox.setObjectName("mainBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.mainBox)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.formLayout_2.setObjectName("formLayout_2")
        self.enter_emailLabel = QtWidgets.QLabel(parent=self.mainBox)
        self.enter_emailLabel.setObjectName("enter_emailLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.enter_emailLabel)
        self.email_input = QtWidgets.QLineEdit(parent=self.mainBox)
        self.email_input.setMinimumSize(QtCore.QSize(201, 20))
        self.email_input.setMaximumSize(QtCore.QSize(201, 20))
        self.email_input.setObjectName("email_input")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.email_input)
        self.enter_passwordLabel = QtWidgets.QLabel(parent=self.mainBox)
        self.enter_passwordLabel.setObjectName("enter_passwordLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.enter_passwordLabel)
        self.password_input = QtWidgets.QLineEdit(parent=self.mainBox)
        self.password_input.setMinimumSize(QtCore.QSize(201, 20))
        self.password_input.setMaximumSize(QtCore.QSize(201, 20))
        self.password_input.setObjectName("password_input")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.password_input)
        self.buttonsBox = QtWidgets.QGroupBox(parent=self.mainBox)
        self.buttonsBox.setMinimumSize(QtCore.QSize(481, 31))
        self.buttonsBox.setMaximumSize(QtCore.QSize(481, 31))
        self.buttonsBox.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 145, 217);\n"
"    border: none;\n"
"}")
        self.buttonsBox.setTitle("")
        self.buttonsBox.setObjectName("buttonsBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonsBox)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginButton = QtWidgets.QPushButton(parent=self.buttonsBox)
        self.loginButton.setMinimumSize(QtCore.QSize(75, 23))
        self.loginButton.setMaximumSize(QtCore.QSize(75, 23))
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.buttonsBox)
        self.statusLabel = QtWidgets.QLabel(parent=self.mainBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.statusLabel.setFont(font)
        self.statusLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.statusLabel.setStyleSheet("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.statusLabel)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.mainBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 483, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "Simple Login Page"))
        self.enter_emailLabel.setText(_translate("MainWindow", "Enter Email:"))
        self.enter_passwordLabel.setText(_translate("MainWindow", "Enter Password:"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.statusLabel.setText(_translate("MainWindow", "Status: Logged Out "))
