from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 373)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(640, 332))
        self.centralwidget.setMaximumSize(QtCore.QSize(640, 332))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iconsLabel_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.iconsLabel_2.setAutoFillBackground(False)
        self.iconsLabel_2.setStyleSheet("QLabel {\n"
"    background-color: rgb(240, 240, 240);\n"
"    font-size: 24pt;\n"
"    border-left: 4px solid black;\n"
"    border-bottom: 4px solid black;\n"
"    padding: 2px;\n"
"}")
        self.iconsLabel_2.setText("")
        self.iconsLabel_2.setPixmap(QtGui.QPixmap("Cafe Management System/Screenshot 2025-04-08 215506.png"))
        self.iconsLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.iconsLabel_2.setObjectName("iconsLabel_2")
        self.horizontalLayout.addWidget(self.iconsLabel_2)
        self.CafeManagementSytemsLabel = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(87)
        self.CafeManagementSytemsLabel.setFont(font)
        self.CafeManagementSytemsLabel.setAutoFillBackground(False)
        self.CafeManagementSytemsLabel.setStyleSheet("QLabel {\n"
"    background-color: rgb(240, 240, 240);\n"
"    font-size: 28pt;\n"
"    border-right: 4px solid black;\n"
"    border-bottom: 4px solid black;\n"
"    padding: 2px;\n"
"    font-weight: 700;\n"
"}")
        self.CafeManagementSytemsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.CafeManagementSytemsLabel.setObjectName("CafeManagementSytemsLabel")
        self.horizontalLayout.addWidget(self.CafeManagementSytemsLabel)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 4)
        self.drinksBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.drinksBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(240, 240, 240);\n"
"    border: 1px solid black;\n"
"    border-left: 4px solid black;\n"
"}")
        self.drinksBox_2.setTitle("")
        self.drinksBox_2.setCheckable(False)
        self.drinksBox_2.setObjectName("drinksBox_2")
        self.formLayout_7 = QtWidgets.QFormLayout(self.drinksBox_2)
        self.formLayout_7.setObjectName("formLayout_7")
        self.americanCoffeeLabel_2 = QtWidgets.QLabel(parent=self.drinksBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.americanCoffeeLabel_2.setFont(font)
        self.americanCoffeeLabel_2.setMouseTracking(False)
        self.americanCoffeeLabel_2.setTabletTracking(False)
        self.americanCoffeeLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.americanCoffeeLabel_2.setAcceptDrops(False)
        self.americanCoffeeLabel_2.setScaledContents(False)
        self.americanCoffeeLabel_2.setWordWrap(False)
        self.americanCoffeeLabel_2.setObjectName("americanCoffeeLabel_2")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.americanCoffeeLabel_2)
        self.africanCoffeeLabel_2 = QtWidgets.QLabel(parent=self.drinksBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.africanCoffeeLabel_2.setFont(font)
        self.africanCoffeeLabel_2.setMouseTracking(False)
        self.africanCoffeeLabel_2.setTabletTracking(False)
        self.africanCoffeeLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.africanCoffeeLabel_2.setAcceptDrops(False)
        self.africanCoffeeLabel_2.setScaledContents(False)
        self.africanCoffeeLabel_2.setWordWrap(False)
        self.africanCoffeeLabel_2.setObjectName("africanCoffeeLabel_2")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.africanCoffeeLabel_2)
        self.valesLabel_2 = QtWidgets.QLabel(parent=self.drinksBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.valesLabel_2.setFont(font)
        self.valesLabel_2.setMouseTracking(False)
        self.valesLabel_2.setTabletTracking(False)
        self.valesLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.valesLabel_2.setAcceptDrops(False)
        self.valesLabel_2.setScaledContents(False)
        self.valesLabel_2.setWordWrap(False)
        self.valesLabel_2.setObjectName("valesLabel_2")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.valesLabel_2)
        self.CappuccinoLabel_2 = QtWidgets.QLabel(parent=self.drinksBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CappuccinoLabel_2.setFont(font)
        self.CappuccinoLabel_2.setMouseTracking(False)
        self.CappuccinoLabel_2.setTabletTracking(False)
        self.CappuccinoLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.CappuccinoLabel_2.setAcceptDrops(False)
        self.CappuccinoLabel_2.setScaledContents(False)
        self.CappuccinoLabel_2.setWordWrap(False)
        self.CappuccinoLabel_2.setObjectName("CappuccinoLabel_2")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.CappuccinoLabel_2)
        self.icedlatteLabel_2 = QtWidgets.QLabel(parent=self.drinksBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.icedlatteLabel_2.setFont(font)
        self.icedlatteLabel_2.setMouseTracking(False)
        self.icedlatteLabel_2.setTabletTracking(False)
        self.icedlatteLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.icedlatteLabel_2.setAcceptDrops(False)
        self.icedlatteLabel_2.setScaledContents(False)
        self.icedlatteLabel_2.setWordWrap(False)
        self.icedlatteLabel_2.setObjectName("icedlatteLabel_2")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.icedlatteLabel_2)
        self.drinksSpinBox_american_2 = QtWidgets.QSpinBox(parent=self.drinksBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drinksSpinBox_american_2.sizePolicy().hasHeightForWidth())
        self.drinksSpinBox_american_2.setSizePolicy(sizePolicy)
        self.drinksSpinBox_american_2.setMaximumSize(QtCore.QSize(39, 18))
        self.drinksSpinBox_american_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.drinksSpinBox_american_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.drinksSpinBox_american_2.setStyleSheet("")
        self.drinksSpinBox_american_2.setWrapping(False)
        self.drinksSpinBox_american_2.setFrame(False)
        self.drinksSpinBox_american_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drinksSpinBox_american_2.setReadOnly(False)
        self.drinksSpinBox_american_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.drinksSpinBox_american_2.setKeyboardTracking(True)
        self.drinksSpinBox_american_2.setProperty("showGroupSeparator", False)
        self.drinksSpinBox_american_2.setObjectName("drinksSpinBox_american_2")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.drinksSpinBox_american_2)
        self.drinksSpinBox_african_2 = QtWidgets.QSpinBox(parent=self.drinksBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drinksSpinBox_african_2.sizePolicy().hasHeightForWidth())
        self.drinksSpinBox_african_2.setSizePolicy(sizePolicy)
        self.drinksSpinBox_african_2.setMaximumSize(QtCore.QSize(39, 18))
        self.drinksSpinBox_african_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.drinksSpinBox_african_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.drinksSpinBox_african_2.setStyleSheet("")
        self.drinksSpinBox_african_2.setWrapping(False)
        self.drinksSpinBox_african_2.setFrame(False)
        self.drinksSpinBox_african_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drinksSpinBox_african_2.setReadOnly(False)
        self.drinksSpinBox_african_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.drinksSpinBox_african_2.setKeyboardTracking(True)
        self.drinksSpinBox_african_2.setProperty("showGroupSeparator", False)
        self.drinksSpinBox_african_2.setObjectName("drinksSpinBox_african_2")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.drinksSpinBox_african_2)
        self.drinksSpinBox_vales_2 = QtWidgets.QSpinBox(parent=self.drinksBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drinksSpinBox_vales_2.sizePolicy().hasHeightForWidth())
        self.drinksSpinBox_vales_2.setSizePolicy(sizePolicy)
        self.drinksSpinBox_vales_2.setMaximumSize(QtCore.QSize(39, 17))
        self.drinksSpinBox_vales_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.drinksSpinBox_vales_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.drinksSpinBox_vales_2.setStyleSheet("")
        self.drinksSpinBox_vales_2.setWrapping(False)
        self.drinksSpinBox_vales_2.setFrame(False)
        self.drinksSpinBox_vales_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drinksSpinBox_vales_2.setReadOnly(False)
        self.drinksSpinBox_vales_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.drinksSpinBox_vales_2.setKeyboardTracking(True)
        self.drinksSpinBox_vales_2.setProperty("showGroupSeparator", False)
        self.drinksSpinBox_vales_2.setObjectName("drinksSpinBox_vales_2")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.drinksSpinBox_vales_2)
        self.drinksSpinBox_cappuccino_2 = QtWidgets.QSpinBox(parent=self.drinksBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drinksSpinBox_cappuccino_2.sizePolicy().hasHeightForWidth())
        self.drinksSpinBox_cappuccino_2.setSizePolicy(sizePolicy)
        self.drinksSpinBox_cappuccino_2.setMaximumSize(QtCore.QSize(39, 18))
        self.drinksSpinBox_cappuccino_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.drinksSpinBox_cappuccino_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.drinksSpinBox_cappuccino_2.setStyleSheet("")
        self.drinksSpinBox_cappuccino_2.setWrapping(False)
        self.drinksSpinBox_cappuccino_2.setFrame(False)
        self.drinksSpinBox_cappuccino_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drinksSpinBox_cappuccino_2.setReadOnly(False)
        self.drinksSpinBox_cappuccino_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.drinksSpinBox_cappuccino_2.setKeyboardTracking(True)
        self.drinksSpinBox_cappuccino_2.setProperty("showGroupSeparator", False)
        self.drinksSpinBox_cappuccino_2.setObjectName("drinksSpinBox_cappuccino_2")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.drinksSpinBox_cappuccino_2)
        self.drinksSpinBox_icedlatte_2 = QtWidgets.QSpinBox(parent=self.drinksBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drinksSpinBox_icedlatte_2.sizePolicy().hasHeightForWidth())
        self.drinksSpinBox_icedlatte_2.setSizePolicy(sizePolicy)
        self.drinksSpinBox_icedlatte_2.setMaximumSize(QtCore.QSize(39, 18))
        self.drinksSpinBox_icedlatte_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.drinksSpinBox_icedlatte_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.drinksSpinBox_icedlatte_2.setStyleSheet("")
        self.drinksSpinBox_icedlatte_2.setWrapping(False)
        self.drinksSpinBox_icedlatte_2.setFrame(False)
        self.drinksSpinBox_icedlatte_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drinksSpinBox_icedlatte_2.setReadOnly(False)
        self.drinksSpinBox_icedlatte_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.drinksSpinBox_icedlatte_2.setKeyboardTracking(True)
        self.drinksSpinBox_icedlatte_2.setProperty("showGroupSeparator", False)
        self.drinksSpinBox_icedlatte_2.setObjectName("drinksSpinBox_icedlatte_2")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.drinksSpinBox_icedlatte_2)
        self.espressoLabel_2 = QtWidgets.QLabel(parent=self.drinksBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.espressoLabel_2.setFont(font)
        self.espressoLabel_2.setMouseTracking(False)
        self.espressoLabel_2.setTabletTracking(False)
        self.espressoLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.espressoLabel_2.setAcceptDrops(False)
        self.espressoLabel_2.setScaledContents(False)
        self.espressoLabel_2.setWordWrap(False)
        self.espressoLabel_2.setObjectName("espressoLabel_2")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.espressoLabel_2)
        self.latteLabel_2 = QtWidgets.QLabel(parent=self.drinksBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.latteLabel_2.setFont(font)
        self.latteLabel_2.setMouseTracking(False)
        self.latteLabel_2.setTabletTracking(False)
        self.latteLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.latteLabel_2.setAcceptDrops(False)
        self.latteLabel_2.setScaledContents(False)
        self.latteLabel_2.setWordWrap(False)
        self.latteLabel_2.setObjectName("latteLabel_2")
        self.formLayout_7.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.latteLabel_2)
        self.drinksSpinBox_espresso_2 = QtWidgets.QSpinBox(parent=self.drinksBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drinksSpinBox_espresso_2.sizePolicy().hasHeightForWidth())
        self.drinksSpinBox_espresso_2.setSizePolicy(sizePolicy)
        self.drinksSpinBox_espresso_2.setMaximumSize(QtCore.QSize(39, 18))
        self.drinksSpinBox_espresso_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.drinksSpinBox_espresso_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.drinksSpinBox_espresso_2.setStyleSheet("")
        self.drinksSpinBox_espresso_2.setWrapping(False)
        self.drinksSpinBox_espresso_2.setFrame(False)
        self.drinksSpinBox_espresso_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drinksSpinBox_espresso_2.setReadOnly(False)
        self.drinksSpinBox_espresso_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.drinksSpinBox_espresso_2.setKeyboardTracking(True)
        self.drinksSpinBox_espresso_2.setProperty("showGroupSeparator", False)
        self.drinksSpinBox_espresso_2.setObjectName("drinksSpinBox_espresso_2")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.drinksSpinBox_espresso_2)
        self.drinksSpinBox_latte_2 = QtWidgets.QSpinBox(parent=self.drinksBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drinksSpinBox_latte_2.sizePolicy().hasHeightForWidth())
        self.drinksSpinBox_latte_2.setSizePolicy(sizePolicy)
        self.drinksSpinBox_latte_2.setMaximumSize(QtCore.QSize(39, 18))
        self.drinksSpinBox_latte_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.drinksSpinBox_latte_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.drinksSpinBox_latte_2.setStyleSheet("")
        self.drinksSpinBox_latte_2.setWrapping(False)
        self.drinksSpinBox_latte_2.setFrame(False)
        self.drinksSpinBox_latte_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drinksSpinBox_latte_2.setReadOnly(False)
        self.drinksSpinBox_latte_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.drinksSpinBox_latte_2.setKeyboardTracking(True)
        self.drinksSpinBox_latte_2.setProperty("showGroupSeparator", False)
        self.drinksSpinBox_latte_2.setObjectName("drinksSpinBox_latte_2")
        self.formLayout_7.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.drinksSpinBox_latte_2)
        self.icedCappuccinoLabel_2 = QtWidgets.QLabel(parent=self.drinksBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.icedCappuccinoLabel_2.setFont(font)
        self.icedCappuccinoLabel_2.setMouseTracking(False)
        self.icedCappuccinoLabel_2.setTabletTracking(False)
        self.icedCappuccinoLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.icedCappuccinoLabel_2.setAcceptDrops(False)
        self.icedCappuccinoLabel_2.setScaledContents(False)
        self.icedCappuccinoLabel_2.setWordWrap(False)
        self.icedCappuccinoLabel_2.setObjectName("icedCappuccinoLabel_2")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.icedCappuccinoLabel_2)
        self.drinksSpinBox_icedCap_3 = QtWidgets.QSpinBox(parent=self.drinksBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drinksSpinBox_icedCap_3.sizePolicy().hasHeightForWidth())
        self.drinksSpinBox_icedCap_3.setSizePolicy(sizePolicy)
        self.drinksSpinBox_icedCap_3.setMaximumSize(QtCore.QSize(39, 18))
        self.drinksSpinBox_icedCap_3.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.drinksSpinBox_icedCap_3.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.drinksSpinBox_icedCap_3.setStyleSheet("")
        self.drinksSpinBox_icedCap_3.setWrapping(False)
        self.drinksSpinBox_icedCap_3.setFrame(False)
        self.drinksSpinBox_icedCap_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.drinksSpinBox_icedCap_3.setReadOnly(False)
        self.drinksSpinBox_icedCap_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.drinksSpinBox_icedCap_3.setKeyboardTracking(True)
        self.drinksSpinBox_icedCap_3.setProperty("showGroupSeparator", False)
        self.drinksSpinBox_icedCap_3.setObjectName("drinksSpinBox_icedCap_3")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.drinksSpinBox_icedCap_3)
        self.gridLayout.addWidget(self.drinksBox_2, 1, 0, 1, 1)
        self.cakeBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.cakeBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(240, 240, 240);\n"
"    border: 2px solid black;\n"
"    padding: 2px;\n"
"}")
        self.cakeBox_2.setTitle("")
        self.cakeBox_2.setObjectName("cakeBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.cakeBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.chocoLabel_2 = QtWidgets.QLabel(parent=self.cakeBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chocoLabel_2.setFont(font)
        self.chocoLabel_2.setMouseTracking(False)
        self.chocoLabel_2.setTabletTracking(False)
        self.chocoLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.chocoLabel_2.setAcceptDrops(False)
        self.chocoLabel_2.setScaledContents(False)
        self.chocoLabel_2.setWordWrap(False)
        self.chocoLabel_2.setObjectName("chocoLabel_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.chocoLabel_2)
        self.chocoSpinBox_queens_2 = QtWidgets.QSpinBox(parent=self.cakeBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chocoSpinBox_queens_2.sizePolicy().hasHeightForWidth())
        self.chocoSpinBox_queens_2.setSizePolicy(sizePolicy)
        self.chocoSpinBox_queens_2.setMaximumSize(QtCore.QSize(39, 16))
        self.chocoSpinBox_queens_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.chocoSpinBox_queens_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.chocoSpinBox_queens_2.setStyleSheet("")
        self.chocoSpinBox_queens_2.setWrapping(False)
        self.chocoSpinBox_queens_2.setFrame(False)
        self.chocoSpinBox_queens_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chocoSpinBox_queens_2.setReadOnly(False)
        self.chocoSpinBox_queens_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.chocoSpinBox_queens_2.setKeyboardTracking(True)
        self.chocoSpinBox_queens_2.setProperty("showGroupSeparator", False)
        self.chocoSpinBox_queens_2.setObjectName("chocoSpinBox_queens_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.chocoSpinBox_queens_2)
        self.carltonLabel_2 = QtWidgets.QLabel(parent=self.cakeBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.carltonLabel_2.setFont(font)
        self.carltonLabel_2.setMouseTracking(False)
        self.carltonLabel_2.setTabletTracking(False)
        self.carltonLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.carltonLabel_2.setAcceptDrops(False)
        self.carltonLabel_2.setScaledContents(False)
        self.carltonLabel_2.setWordWrap(False)
        self.carltonLabel_2.setObjectName("carltonLabel_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.carltonLabel_2)
        self.chocoSpinBox_carlton_2 = QtWidgets.QSpinBox(parent=self.cakeBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chocoSpinBox_carlton_2.sizePolicy().hasHeightForWidth())
        self.chocoSpinBox_carlton_2.setSizePolicy(sizePolicy)
        self.chocoSpinBox_carlton_2.setMaximumSize(QtCore.QSize(39, 18))
        self.chocoSpinBox_carlton_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.chocoSpinBox_carlton_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.chocoSpinBox_carlton_2.setStyleSheet("")
        self.chocoSpinBox_carlton_2.setWrapping(False)
        self.chocoSpinBox_carlton_2.setFrame(False)
        self.chocoSpinBox_carlton_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chocoSpinBox_carlton_2.setReadOnly(False)
        self.chocoSpinBox_carlton_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.chocoSpinBox_carlton_2.setKeyboardTracking(True)
        self.chocoSpinBox_carlton_2.setProperty("showGroupSeparator", False)
        self.chocoSpinBox_carlton_2.setObjectName("chocoSpinBox_carlton_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.chocoSpinBox_carlton_2)
        self.kilburnLabel_2 = QtWidgets.QLabel(parent=self.cakeBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kilburnLabel_2.setFont(font)
        self.kilburnLabel_2.setMouseTracking(False)
        self.kilburnLabel_2.setTabletTracking(False)
        self.kilburnLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.kilburnLabel_2.setAcceptDrops(False)
        self.kilburnLabel_2.setScaledContents(False)
        self.kilburnLabel_2.setWordWrap(False)
        self.kilburnLabel_2.setObjectName("kilburnLabel_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.kilburnLabel_2)
        self.chocoSpinBox_kilburn_2 = QtWidgets.QSpinBox(parent=self.cakeBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chocoSpinBox_kilburn_2.sizePolicy().hasHeightForWidth())
        self.chocoSpinBox_kilburn_2.setSizePolicy(sizePolicy)
        self.chocoSpinBox_kilburn_2.setMaximumSize(QtCore.QSize(39, 18))
        self.chocoSpinBox_kilburn_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.chocoSpinBox_kilburn_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.chocoSpinBox_kilburn_2.setStyleSheet("")
        self.chocoSpinBox_kilburn_2.setWrapping(False)
        self.chocoSpinBox_kilburn_2.setFrame(False)
        self.chocoSpinBox_kilburn_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chocoSpinBox_kilburn_2.setReadOnly(False)
        self.chocoSpinBox_kilburn_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.chocoSpinBox_kilburn_2.setKeyboardTracking(True)
        self.chocoSpinBox_kilburn_2.setProperty("showGroupSeparator", False)
        self.chocoSpinBox_kilburn_2.setObjectName("chocoSpinBox_kilburn_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.chocoSpinBox_kilburn_2)
        self.lagosLabel_2 = QtWidgets.QLabel(parent=self.cakeBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lagosLabel_2.setFont(font)
        self.lagosLabel_2.setMouseTracking(False)
        self.lagosLabel_2.setTabletTracking(False)
        self.lagosLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.lagosLabel_2.setAcceptDrops(False)
        self.lagosLabel_2.setScaledContents(False)
        self.lagosLabel_2.setWordWrap(False)
        self.lagosLabel_2.setObjectName("lagosLabel_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lagosLabel_2)
        self.chocoSpinBox_lagos_2 = QtWidgets.QSpinBox(parent=self.cakeBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chocoSpinBox_lagos_2.sizePolicy().hasHeightForWidth())
        self.chocoSpinBox_lagos_2.setSizePolicy(sizePolicy)
        self.chocoSpinBox_lagos_2.setMaximumSize(QtCore.QSize(39, 17))
        self.chocoSpinBox_lagos_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.chocoSpinBox_lagos_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.chocoSpinBox_lagos_2.setStyleSheet("")
        self.chocoSpinBox_lagos_2.setWrapping(False)
        self.chocoSpinBox_lagos_2.setFrame(False)
        self.chocoSpinBox_lagos_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chocoSpinBox_lagos_2.setReadOnly(False)
        self.chocoSpinBox_lagos_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.chocoSpinBox_lagos_2.setKeyboardTracking(True)
        self.chocoSpinBox_lagos_2.setProperty("showGroupSeparator", False)
        self.chocoSpinBox_lagos_2.setObjectName("chocoSpinBox_lagos_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.chocoSpinBox_lagos_2)
        self.bostonLabel_2 = QtWidgets.QLabel(parent=self.cakeBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bostonLabel_2.setFont(font)
        self.bostonLabel_2.setMouseTracking(False)
        self.bostonLabel_2.setTabletTracking(False)
        self.bostonLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.bostonLabel_2.setAcceptDrops(False)
        self.bostonLabel_2.setScaledContents(False)
        self.bostonLabel_2.setWordWrap(False)
        self.bostonLabel_2.setObjectName("bostonLabel_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.bostonLabel_2)
        self.chocoSpinBox_boston_2 = QtWidgets.QSpinBox(parent=self.cakeBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chocoSpinBox_boston_2.sizePolicy().hasHeightForWidth())
        self.chocoSpinBox_boston_2.setSizePolicy(sizePolicy)
        self.chocoSpinBox_boston_2.setMaximumSize(QtCore.QSize(39, 18))
        self.chocoSpinBox_boston_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.chocoSpinBox_boston_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.chocoSpinBox_boston_2.setStyleSheet("")
        self.chocoSpinBox_boston_2.setWrapping(False)
        self.chocoSpinBox_boston_2.setFrame(False)
        self.chocoSpinBox_boston_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chocoSpinBox_boston_2.setReadOnly(False)
        self.chocoSpinBox_boston_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.chocoSpinBox_boston_2.setKeyboardTracking(True)
        self.chocoSpinBox_boston_2.setProperty("showGroupSeparator", False)
        self.chocoSpinBox_boston_2.setObjectName("chocoSpinBox_boston_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.chocoSpinBox_boston_2)
        self.blackforestLabel_2 = QtWidgets.QLabel(parent=self.cakeBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.blackforestLabel_2.setFont(font)
        self.blackforestLabel_2.setMouseTracking(False)
        self.blackforestLabel_2.setTabletTracking(False)
        self.blackforestLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.blackforestLabel_2.setAcceptDrops(False)
        self.blackforestLabel_2.setScaledContents(False)
        self.blackforestLabel_2.setWordWrap(False)
        self.blackforestLabel_2.setObjectName("blackforestLabel_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.blackforestLabel_2)
        self.chocoSpinBox_blackforest_2 = QtWidgets.QSpinBox(parent=self.cakeBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chocoSpinBox_blackforest_2.sizePolicy().hasHeightForWidth())
        self.chocoSpinBox_blackforest_2.setSizePolicy(sizePolicy)
        self.chocoSpinBox_blackforest_2.setMaximumSize(QtCore.QSize(39, 18))
        self.chocoSpinBox_blackforest_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.chocoSpinBox_blackforest_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.chocoSpinBox_blackforest_2.setStyleSheet("")
        self.chocoSpinBox_blackforest_2.setWrapping(False)
        self.chocoSpinBox_blackforest_2.setFrame(False)
        self.chocoSpinBox_blackforest_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chocoSpinBox_blackforest_2.setReadOnly(False)
        self.chocoSpinBox_blackforest_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.chocoSpinBox_blackforest_2.setKeyboardTracking(True)
        self.chocoSpinBox_blackforest_2.setProperty("showGroupSeparator", False)
        self.chocoSpinBox_blackforest_2.setObjectName("chocoSpinBox_blackforest_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.chocoSpinBox_blackforest_2)
        self.rvLabel_2 = QtWidgets.QLabel(parent=self.cakeBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rvLabel_2.setFont(font)
        self.rvLabel_2.setMouseTracking(False)
        self.rvLabel_2.setTabletTracking(False)
        self.rvLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.rvLabel_2.setAcceptDrops(False)
        self.rvLabel_2.setScaledContents(False)
        self.rvLabel_2.setWordWrap(False)
        self.rvLabel_2.setObjectName("rvLabel_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rvLabel_2)
        self.chocoSpinBox_redvelvet_2 = QtWidgets.QSpinBox(parent=self.cakeBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chocoSpinBox_redvelvet_2.sizePolicy().hasHeightForWidth())
        self.chocoSpinBox_redvelvet_2.setSizePolicy(sizePolicy)
        self.chocoSpinBox_redvelvet_2.setMaximumSize(QtCore.QSize(39, 18))
        self.chocoSpinBox_redvelvet_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.chocoSpinBox_redvelvet_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.chocoSpinBox_redvelvet_2.setStyleSheet("")
        self.chocoSpinBox_redvelvet_2.setWrapping(False)
        self.chocoSpinBox_redvelvet_2.setFrame(False)
        self.chocoSpinBox_redvelvet_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chocoSpinBox_redvelvet_2.setReadOnly(False)
        self.chocoSpinBox_redvelvet_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.chocoSpinBox_redvelvet_2.setKeyboardTracking(True)
        self.chocoSpinBox_redvelvet_2.setProperty("showGroupSeparator", False)
        self.chocoSpinBox_redvelvet_2.setObjectName("chocoSpinBox_redvelvet_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.chocoSpinBox_redvelvet_2)
        self.coffeecakeLabel_2 = QtWidgets.QLabel(parent=self.cakeBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.coffeecakeLabel_2.setFont(font)
        self.coffeecakeLabel_2.setMouseTracking(False)
        self.coffeecakeLabel_2.setTabletTracking(False)
        self.coffeecakeLabel_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.coffeecakeLabel_2.setAcceptDrops(False)
        self.coffeecakeLabel_2.setScaledContents(False)
        self.coffeecakeLabel_2.setWordWrap(False)
        self.coffeecakeLabel_2.setObjectName("coffeecakeLabel_2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.coffeecakeLabel_2)
        self.chocoSpinBox_coffeecake_2 = QtWidgets.QSpinBox(parent=self.cakeBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chocoSpinBox_coffeecake_2.sizePolicy().hasHeightForWidth())
        self.chocoSpinBox_coffeecake_2.setSizePolicy(sizePolicy)
        self.chocoSpinBox_coffeecake_2.setMaximumSize(QtCore.QSize(39, 18))
        self.chocoSpinBox_coffeecake_2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.chocoSpinBox_coffeecake_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.chocoSpinBox_coffeecake_2.setStyleSheet("")
        self.chocoSpinBox_coffeecake_2.setWrapping(False)
        self.chocoSpinBox_coffeecake_2.setFrame(False)
        self.chocoSpinBox_coffeecake_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chocoSpinBox_coffeecake_2.setReadOnly(False)
        self.chocoSpinBox_coffeecake_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.chocoSpinBox_coffeecake_2.setKeyboardTracking(True)
        self.chocoSpinBox_coffeecake_2.setProperty("showGroupSeparator", False)
        self.chocoSpinBox_coffeecake_2.setObjectName("chocoSpinBox_coffeecake_2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.chocoSpinBox_coffeecake_2)
        self.gridLayout.addWidget(self.cakeBox_2, 1, 1, 1, 2)
        self.receiptBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.receiptBrowser.setStyleSheet("QTextBrowser {\n"
"    background-color: rgb(240, 240, 240);\n"
"    font-size: 28pt;\n"
"    border-right: 4px solid black;\n"
"    border-bottom: 2px solid black;\n"
"    border-left: 2px solid black;\n"
"    padding: 2px;\n"
"}")
        self.receiptBrowser.setObjectName("receiptBrowser")
        self.gridLayout.addWidget(self.receiptBrowser, 1, 3, 2, 1)
        self.costBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.costBox.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(240, 240, 240);\n"
"    border: 2px solid black;\n"
"    border-left: 4px solid black;\n"
"    border-right: 1px solid black;\n"
"}")
        self.costBox.setTitle("")
        self.costBox.setCheckable(False)
        self.costBox.setObjectName("costBox")
        self.formLayout_5 = QtWidgets.QFormLayout(self.costBox)
        self.formLayout_5.setObjectName("formLayout_5")
        self.costDrinkLabel = QtWidgets.QLabel(parent=self.costBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.costDrinkLabel.setFont(font)
        self.costDrinkLabel.setMouseTracking(False)
        self.costDrinkLabel.setTabletTracking(False)
        self.costDrinkLabel.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.costDrinkLabel.setAcceptDrops(False)
        self.costDrinkLabel.setScaledContents(False)
        self.costDrinkLabel.setWordWrap(False)
        self.costDrinkLabel.setObjectName("costDrinkLabel")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.costDrinkLabel)
        self.costcakesLabel = QtWidgets.QLabel(parent=self.costBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.costcakesLabel.setFont(font)
        self.costcakesLabel.setMouseTracking(False)
        self.costcakesLabel.setTabletTracking(False)
        self.costcakesLabel.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.costcakesLabel.setAcceptDrops(False)
        self.costcakesLabel.setScaledContents(False)
        self.costcakesLabel.setWordWrap(False)
        self.costcakesLabel.setObjectName("costcakesLabel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.costcakesLabel)
        self.servicechargeLabel = QtWidgets.QLabel(parent=self.costBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.servicechargeLabel.setFont(font)
        self.servicechargeLabel.setMouseTracking(False)
        self.servicechargeLabel.setTabletTracking(False)
        self.servicechargeLabel.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.servicechargeLabel.setAcceptDrops(False)
        self.servicechargeLabel.setScaledContents(False)
        self.servicechargeLabel.setWordWrap(False)
        self.servicechargeLabel.setObjectName("servicechargeLabel")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.servicechargeLabel)
        self.costdrinksSpinBox = QtWidgets.QDoubleSpinBox(parent=self.costBox)
        self.costdrinksSpinBox.setMinimumSize(QtCore.QSize(68, 13))
        self.costdrinksSpinBox.setMaximumSize(QtCore.QSize(68, 13))
        self.costdrinksSpinBox.setFrame(False)
        self.costdrinksSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.costdrinksSpinBox.setReadOnly(True)
        self.costdrinksSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.costdrinksSpinBox.setObjectName("costdrinksSpinBox")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.costdrinksSpinBox)
        self.costcakesSpinBox = QtWidgets.QDoubleSpinBox(parent=self.costBox)
        self.costcakesSpinBox.setMinimumSize(QtCore.QSize(68, 13))
        self.costcakesSpinBox.setMaximumSize(QtCore.QSize(68, 13))
        self.costcakesSpinBox.setFrame(False)
        self.costcakesSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.costcakesSpinBox.setReadOnly(True)
        self.costcakesSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.costcakesSpinBox.setObjectName("costcakesSpinBox")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.costcakesSpinBox)
        self.servicechargeSpinBox = QtWidgets.QDoubleSpinBox(parent=self.costBox)
        self.servicechargeSpinBox.setMinimumSize(QtCore.QSize(68, 13))
        self.servicechargeSpinBox.setMaximumSize(QtCore.QSize(68, 13))
        self.servicechargeSpinBox.setFrame(False)
        self.servicechargeSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.servicechargeSpinBox.setReadOnly(True)
        self.servicechargeSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.servicechargeSpinBox.setObjectName("servicechargeSpinBox")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.servicechargeSpinBox)
        self.gridLayout.addWidget(self.costBox, 2, 0, 2, 2)
        self.totalBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.totalBox.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(240, 240, 240);\n"
"    border: 2px solid black;\n"
"    border-left: 2px solid black;\n"
"    border-right: 1px solid black;\n"
"}")
        self.totalBox.setTitle("")
        self.totalBox.setCheckable(False)
        self.totalBox.setObjectName("totalBox")
        self.formLayout_6 = QtWidgets.QFormLayout(self.totalBox)
        self.formLayout_6.setObjectName("formLayout_6")
        self.taxonorderLabel = QtWidgets.QLabel(parent=self.totalBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.taxonorderLabel.setFont(font)
        self.taxonorderLabel.setMouseTracking(False)
        self.taxonorderLabel.setTabletTracking(False)
        self.taxonorderLabel.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.taxonorderLabel.setAcceptDrops(False)
        self.taxonorderLabel.setScaledContents(False)
        self.taxonorderLabel.setWordWrap(False)
        self.taxonorderLabel.setObjectName("taxonorderLabel")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.taxonorderLabel)
        self.subtotalLabel = QtWidgets.QLabel(parent=self.totalBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subtotalLabel.setFont(font)
        self.subtotalLabel.setMouseTracking(False)
        self.subtotalLabel.setTabletTracking(False)
        self.subtotalLabel.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.subtotalLabel.setAcceptDrops(False)
        self.subtotalLabel.setScaledContents(False)
        self.subtotalLabel.setWordWrap(False)
        self.subtotalLabel.setObjectName("subtotalLabel")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.subtotalLabel)
        self.totalLabel = QtWidgets.QLabel(parent=self.totalBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.totalLabel.setFont(font)
        self.totalLabel.setMouseTracking(False)
        self.totalLabel.setTabletTracking(False)
        self.totalLabel.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.totalLabel.setAcceptDrops(False)
        self.totalLabel.setScaledContents(False)
        self.totalLabel.setWordWrap(False)
        self.totalLabel.setObjectName("totalLabel")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.totalLabel)
        self.taxonorderSpinBox = QtWidgets.QDoubleSpinBox(parent=self.totalBox)
        self.taxonorderSpinBox.setMaximumSize(QtCore.QSize(68, 13))
        self.taxonorderSpinBox.setFrame(False)
        self.taxonorderSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.taxonorderSpinBox.setReadOnly(True)
        self.taxonorderSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.taxonorderSpinBox.setObjectName("taxonorderSpinBox")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.taxonorderSpinBox)
        self.subtotalSpinBox = QtWidgets.QDoubleSpinBox(parent=self.totalBox)
        self.subtotalSpinBox.setMaximumSize(QtCore.QSize(68, 13))
        self.subtotalSpinBox.setFrame(False)
        self.subtotalSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.subtotalSpinBox.setReadOnly(True)
        self.subtotalSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.subtotalSpinBox.setObjectName("subtotalSpinBox")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.subtotalSpinBox)
        self.totalSpinBox = QtWidgets.QDoubleSpinBox(parent=self.totalBox)
        self.totalSpinBox.setMaximumSize(QtCore.QSize(68, 13))
        self.totalSpinBox.setFrame(False)
        self.totalSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.totalSpinBox.setReadOnly(True)
        self.totalSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.totalSpinBox.setObjectName("totalSpinBox")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.totalSpinBox)
        self.gridLayout.addWidget(self.totalBox, 2, 2, 2, 1)
        self.receiptButtonBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.receiptButtonBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(240, 240, 240);\n"
"    border: 2px solid black;\n"
"    border-right: 4px solid black;\n"
"}")
        self.receiptButtonBox_2.setTitle("")
        self.receiptButtonBox_2.setObjectName("receiptButtonBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.receiptButtonBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.receiptButton_2 = QtWidgets.QPushButton(parent=self.receiptButtonBox_2)
        self.receiptButton_2.setObjectName("receiptButton_2")
        self.horizontalLayout_3.addWidget(self.receiptButton_2)
        self.totalButton_2 = QtWidgets.QPushButton(parent=self.receiptButtonBox_2)
        self.totalButton_2.setObjectName("totalButton_2")
        self.horizontalLayout_3.addWidget(self.totalButton_2)
        self.resetButton_2 = QtWidgets.QPushButton(parent=self.receiptButtonBox_2)
        self.resetButton_2.setObjectName("resetButton_2")
        self.horizontalLayout_3.addWidget(self.resetButton_2)
        self.exitButton_2 = QtWidgets.QPushButton(parent=self.receiptButtonBox_2)
        self.exitButton_2.setObjectName("exitButton_2")
        self.horizontalLayout_3.addWidget(self.exitButton_2)
        self.gridLayout.addWidget(self.receiptButtonBox_2, 3, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 643, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CafeManagementSytemsLabel.setText(_translate("MainWindow", "Cafe Management System"))
        self.americanCoffeeLabel_2.setText(_translate("MainWindow", "American Coffee"))
        self.africanCoffeeLabel_2.setText(_translate("MainWindow", "African Coffee"))
        self.valesLabel_2.setText(_translate("MainWindow", "Vales Coffee"))
        self.CappuccinoLabel_2.setText(_translate("MainWindow", "Cappuccino"))
        self.icedlatteLabel_2.setText(_translate("MainWindow", "Iced Latte"))
        self.espressoLabel_2.setText(_translate("MainWindow", "Espresso"))
        self.latteLabel_2.setText(_translate("MainWindow", "Latte"))
        self.icedCappuccinoLabel_2.setText(_translate("MainWindow", "Iced - Cappuccino"))
        self.chocoLabel_2.setText(_translate("MainWindow", "Queen\'s Park Chocolate Cake "))
        self.carltonLabel_2.setText(_translate("MainWindow", "Carlton Hill Chocolate Cake "))
        self.kilburnLabel_2.setText(_translate("MainWindow", "Kilburn Chocolate Cake "))
        self.lagosLabel_2.setText(_translate("MainWindow", "Lagos Chocolate Cake "))
        self.bostonLabel_2.setText(_translate("MainWindow", "Boston Cream Cake "))
        self.blackforestLabel_2.setText(_translate("MainWindow", "Black Forest Cake "))
        self.rvLabel_2.setText(_translate("MainWindow", "Red Velvet Cake "))
        self.coffeecakeLabel_2.setText(_translate("MainWindow", "Coffee Cake"))
        self.receiptBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.costDrinkLabel.setText(_translate("MainWindow", "Cost of Drinks       "))
        self.costcakesLabel.setText(_translate("MainWindow", "Cost of Cakes"))
        self.servicechargeLabel.setText(_translate("MainWindow", "Service Charge"))
        self.taxonorderLabel.setText(_translate("MainWindow", "Tax on Order           "))
        self.subtotalLabel.setText(_translate("MainWindow", "Subtotal"))
        self.totalLabel.setText(_translate("MainWindow", "Total"))
        self.receiptButton_2.setText(_translate("MainWindow", "Receipt"))
        self.totalButton_2.setText(_translate("MainWindow", "Total"))
        self.resetButton_2.setText(_translate("MainWindow", "Reset"))
        self.exitButton_2.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())